### ISSUE TITLE
Native check fails with an AttributeError

### ISSUE THREAD

**Issue by jtratner** [chanzuckerberg/miniwdl#120]
Here's an example (if you remove `input{}` section it'll work okay, adding a version line doesn't change anythng).

```
task bcl2fastq220 {
    input {
        Array[File] run_archive
    }
    command {
    }
    output {
        Array[File]+ stats = [""]
    }
    meta {
        type: "native"
    }
}
```

```
$miniwdl check example.wdl
Traceback (most recent call last):
  File ".pyenv/versions/3.6.4/bin/miniwdl", line 10, in <module>
    sys.exit(main())
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/CLI.py", line 32, in main
    check(**vars(args))
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/CLI.py", line 98, in check
    WDL.Lint.lint(doc)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Lint.py", line 64, in lint
    WDL.Walker.Multi([linter for linter in linter_instances if linter.auto_descend])(doc)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Walker.py", line 63, in __call__
    self(ch)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Walker.py", line 63, in __call__
    self(ch)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Walker.py", line 50, in __call__
    ans = self.decl(obj)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Walker.py", line 136, in decl
    w.decl(obj)
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Lint.py", line 660, in decl
    and pt.meta.get("type") == "native"
  File ".pyenv/versions/3.6.4/lib/python3.6/site-packages/WDL/Error.py", line 65, in __eq__
    return self.pos == rhs.pos
AttributeError: 'str' object has no attribute 'pos'
```

**Comment by mlin** [comment]
Sorry, I don't know how my first try got so negligent, but please try v0.1.6 :sheep:
