### ISSUE TITLE
miniwdl 0.6.4 error in "miniwdl run" concerning Docker log driver

### ISSUE THREAD

**Issue by kislyuk** [chanzuckerberg/miniwdl#340]
```
2020-02-11 22:04:13,559 miniwdl-run WARNING docker swarm lists existing miniwdl-related services. This is normal if other miniwdl processes are running concurrently; otherwise, stale state could interfere with this run. To reset it, `docker swarm leave --force`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 501 Server Error: Not Implemented for url: http+docker://localhost/v1.35/containers/5463fa312dbc048c2bb28bfac8135df7e69581d6ed975866a4f09f3c51a4bd19/logs?stderr=1&stdout=1&timestamps=0&follow=0&tail=all

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/miniwdl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 65, in main
    runner(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 476, in runner
    host_limits = initialize_local_docker(logger, client)
  File "/usr/local/lib/python3.6/dist-packages/WDL/_util.py", line 563, in initialize_local_docker
    stdout = detector.logs(stdout=True)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 302, in logs
    return self.client.api.logs(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 855, in logs
    output = self._get_result(container, stream, res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 451, in _get_result
    return self._get_result_tty(stream, res, self._check_is_tty(container))
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 460, in _get_result_tty
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 501 Server Error: Not Implemented ("configured logging driver does not support reading")
```

No error in 0.6.3.

In the past I've had to work around this type of issue when the application expected Docker to use the JSON log driver, but something else (like the awslogs log driver) was the default instead. The incantation was `docker_client.containers.run(..., log_config=docker.types.LogConfig(type=docker.types.LogConfig.types.JSON))`. Hopefully that helps here.

**Comment by mlin** [comment]
@kislyuk Thanks, i believe https://github.com/chanzuckerberg/miniwdl/commit/5f5f4aa8e72d48ba2847e6f8f5e3143cc7ee179e adds that adjustment in the relevant container, which was indeed a change in v0.6.4. Since I don't have a repro of the problem, are you able to try it as a hotpatch?

**Comment by kislyuk** [comment]
@mlin thanks, it seems to work now. I ran `sudo pip3 install git+https://github.com/chanzuckerberg/miniwdl` and I think that did the right thing:
```
>miniwdl --version
miniwdl v0.6.5.dev5
miniwdl.plugin.file_download    gs = WDL.runtime.download:gsutil_downloader     miniwdl 0.6.5.dev5
miniwdl.plugin.file_download    s3 = miniwdl_download_s3parcp:main      miniwdl-download-s3parcp 0.0.1
Cromwell 47
```
The error is gone.
