### ISSUE TITLE
URLs in imports

### ISSUE THREAD

**Issue by leepc12** [chanzuckerberg/miniwdl#366]
Test toy WDL looks like:
```
import "http://mitra.stanford.edu/kundaje/leepc12/test_croo/c.wdl" as sub_c

workflow main {
        call t0
}

task t0 {
        command {
                echo 2 > 2.txt
        }

        output {
                File out2 = glob('*.txt')[0]
        }
        runtime {
                docker : "ubuntu:latest"
        }
}
```

Miniwdl fails to load it:
```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import WDL
wdL^w = WDL.load('main.wdl')l')
Traceback (most recent call last):
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/Tree.py", line 1319, in load_async
    import_max_depth=(import_max_depth - 1),
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/Tree.py", line 1297, in load_async
    read_rslt = await read_source(uri, path, importer)
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/Tree.py", line 1281, in read_source_default
    with open(abspath, "r") as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'http://mitra.stanford.edu/kundaje/leepc12/test_croo/c.wdl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/__init__.py", line 64, in load
    import_max_depth=import_max_depth,
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/Tree.py", line 1356, in load
    import_max_depth=import_max_depth,
  File "/users/leepc12/miniconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/users/leepc12/miniconda3/lib/python3.7/site-packages/WDL/Tree.py", line 1322, in load_async
    raise Error.ImportError(imp.pos, imp.uri) from exn
WDL.Error.ImportError: Failed to import http://mitra.stanford.edu/kundaje/leepc12/test_croo/c.wdl
```

Womtool validation works:
```
$ java -jar ~/.caper/womtool_jar/womtool-47.jar validate main.wdl
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4024M -XX:ParallelGCThreads=1
09:22:20.133 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework

...

09:23:26.468 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.channel.ChannelManager - Adding key: http://mitra.stanford.edu:80 for channel [id: 0x50d3947c, L:/10.112.2.13:41926 - R:mitra.stanford.edu/171.67.96.243:80]
09:23:27.042 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://mitra.stanford.edu:80 : 1
Success!
```

**Comment by mlin** [comment]
Hi @leepc12 when using the `WDL` package programmatically, the [caller has to supply their own subroutine](https://miniwdl.readthedocs.io/en/latest/WDL.html#WDL.load) (read_source) to download source from URI. The reason for this is to avoid constraining the kind of network operation used (e.g. sync or async). Sorry for the inconvenience.

Here's an example from miniwdl's own CLI.py:

https://github.com/chanzuckerberg/miniwdl/blob/fd8ab70010c9fd5bf59fa304320b6ebc68311fac/WDL/CLI.py#L288-L302

(`read_source_default` is exported by the `WDL` package)

**Comment by leepc12** [comment]
Thanks. It works.
```python
import WDL
w = WDL.load(filename, read_source=WDL.CLI.read_source)
```
