### ISSUE TITLE
Uninformative crash when coercing value to string

### ISSUE THREAD

**Issue by kislyuk** [chanzuckerberg/miniwdl#389]
I'm trying to figure out which input this applies to:
```
2020-05-21 14:51:14+00:00 Traceback (most recent call last):
2020-05-21 14:51:14+00:00   File "/usr/local/bin/miniwdl", line 11, in <module>
2020-05-21 14:51:14+00:00     sys.exit(main())
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 72, in main
2020-05-21 14:51:14+00:00     runner(**vars(args))
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 591, in runner
2020-05-21 14:51:14+00:00     root=eff_root,  # if copy_input_files is set, then input files need not reside under the configured root
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 761, in runner_input
2020-05-21 14:51:14+00:00     available_inputs, (target.name if isinstance(target, Workflow) else ""), input_file, root
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/CLI.py", line 854, in runner_input_json_file
2020-05-21 14:51:14+00:00     ans = values_from_json(input_json, available_inputs, namespace=namespace)
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/__init__.py", line 235, in values_from_json
2020-05-21 14:51:14+00:00     ans = ans.bind(key2, Value.from_json(ty, values_json[key]))
2020-05-21 14:51:14+00:00   File "/usr/local/lib/python3.6/dist-packages/WDL/Value.py", line 412, in from_json
2020-05-21 14:51:14+00:00     raise Error.InputError(f"couldn't construct {str(type)} from: {json.dumps(value)}")
2020-05-21 14:51:14+00:00 WDL.Error.InputError: couldn't construct String from: null
```

**Comment by kislyuk** [comment]
This appears to happen when a `null` JSON value is passed for a string input.

For debuggability, I think the error message should contain the name of the input.
