### ISSUE TITLE
cannot use input filenames containing "{{"

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#415]
This is probably a Docker issue:

```
Traceback (most recent call last):
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/services/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlin/src/czi/miniwdl/WDL/runtime/task.py", line 175, in run_local_task
    _try_task(cfg, logger, container, command, terminating)
  File "/home/mlin/src/czi/miniwdl/WDL/runtime/task.py", line 467, in _try_task
    return container.run(logger, command)
  File "/home/mlin/src/czi/miniwdl/WDL/runtime/task_container.py", line 186, in run
    exit_status = self._run(logger, terminating, command)
  File "/home/mlin/src/czi/miniwdl/WDL/runtime/task_container.py", line 468, in _run
    svc = client.services.create(image_tag, **kwargs)
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/models/services.py", line 225, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/api/service.py", line 189, in create_service
    return self._result(
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/mlin/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("rpc error: code = InvalidArgument desc = expanding mounts failed: expanding mount source "/tmp/miniwdl_test_tests.test_7runner.MiscRegressionTests.test_weird_filenames_xzs__oyo/ThisIsAVeryLongFilename abc...xzy1234567890!@{{నేనుÆды.test.ext": template: expansion:1: unexpected bad character U+0C47 'ే' in command")
```

**Comment by mlin** [comment]
we could escape it using `{{ '{{' }}` :man_facepalming:
