### ISSUE TITLE
Allow bypass of flock if filesystem is not flock compatible

### ISSUE THREAD

**Issue by kislyuk** [chanzuckerberg/miniwdl#483]
The following error happens when running miniwdl with a workdir on an EFS directory:
```
2021-03-02 01:12:06.393 miniwdl-run [Errno 9] Bad file descriptor :: error: "OSError"
Traceback (most recent call last):
  File "/usr/local/bin/miniwdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/WDL/CLI.py", line 71, in main
    runner(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/WDL/CLI.py", line 722, in runner
    rundir, output_env = runtime.run(cfg, target, input_env, run_dir=run_dir, _cache=cache)
  File "/usr/local/lib/python3.8/dist-packages/WDL/runtime/__init__.py", line 56, in run
    return entrypoint(cfg, exe, inputs, **run_kwargs)  # pyre-ignore
  File "/usr/local/lib/python3.8/dist-packages/WDL/runtime/task.py", line 98, in run_local_task
    cache.flock(logfile, exclusive=True)  # no containing workflow; flock task.log
  File "/usr/local/lib/python3.8/dist-packages/WDL/runtime/cache.py", line 271, in flock
    self._flocker.flock(filename, update_atime=True, exclusive=exclusive)
  File "/usr/local/lib/python3.8/dist-packages/WDL/_util.py", line 844, in flock
    fcntl.flock(openfile, op)
OSError: [Errno 9] Bad file descriptor
```
Granted, operating miniwdl with the scratch space located on an NFS mount is probably to be discouraged for performance reasons, but it would be nice to be able to bypass this error with an option that would explicitly call out that flocks are disabled on this run.

**Comment by mlin** [comment]
I recently made this yet-unreleased [revert](https://github.com/chanzuckerberg/miniwdl/commit/04ee56b5b795cd45e53c57a9fdf57204e72dbbe2) exactly because of the EFS issues. EFS flock support is pretty good overall; it's just different enough from Linux behavior to cause problems with that commit I reverted:

1. To take an *exclusive* flock, the descriptor must be opened with read/write permissions
2. Cannot flock directories

That revert should unblock EFS, but I agree it seems useful to be able to opt out of flocking entirely.

**Comment by mlin** [comment]
v1.1.1 should improve EFS compatibility. The flocks turn out to be pretty important for updating the download cache which can happen from multiple processes. But I removed some more-exotic things it was doing like trying to flock directories.
