### ISSUE TITLE
PermissionError when running miniwdl with Docker Desktop on Linux

### ISSUE THREAD

**Issue by stxue1** [chanzuckerberg/miniwdl#644]
When running `miniwdl run_self_test` miniwdl fails to chmod the work directories

```
2023-06-07 12:36:11.862 wdl.w:hello_caller.download0.t:download-aria2c Traceback (most recent call last):
  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/runtime/task.py", line 224, in run_local_task
    chmod_R_plus(run_dir, file_bits=0o660, dir_bits=0o770)
  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/_util.py", line 677, in chmod_R_plus
    do1(os.path.join(root, dn), dir_bits)
  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/_util.py", line 668, in do1
    os.chmod(path1, (os.stat(path1).st_mode & 0o7777) | bits)
PermissionError: [Errno 1] Operation not permitted: '/tmp/miniwdl_run_self_test_1ey4kejx/20230607_123607_hello_caller/download/0/work'
```
This might be due to how Docker Desktop on Linux delegates user IDs. The files/directoires that miniwdl tries to chmod is owned by UID 100999, but miniwdl is running as my user UID, which is 1000. This is after I already solved a file sharing problem previously mentioned at #404 where I changed the file sharing directory under the Docker Desktop settings to the root directory.

I'm doing this in the context of trying to get Toil's WDL conformance tests to work.

**Comment by mlin** [comment]
@stxue1 thanks for reporting, I have not tried Docker Desktop on Linux before so I'll need to look into this further. I'm surprised that it leaves files created by the containers owned by some different UID. On macOS it leaves them owned by your UID even though the ownership appears different inside the containers themselves.

A couple things that may be worth trying before I'm able to study the issue:

1. Try [running miniwdl itself inside a container](https://miniwdl.readthedocs.io/en/latest/runner_advanced.html#how-to-miniwdl-run-inside-a-docker-container) in the Docker Desktop VM.
2. Informally comment out line 224 of `/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/runtime/task.py`, the `chmod_R_plus` -- just to see if that unblocks you temporarily. The purpose of the chmod is to make sure downstream containers can access the files even if they internally "drop privileges" to run as some arbitrary UID (neither yours nor root) -- it's a bit of a corner case.

**Comment by mlin** [comment]
@stxue1 Belated follow-up as I was looking into this a little. It might help to set the miniwdl configuration option [`[file_io] chown = false`](https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/config_templates/default.cfg#L85-L89) (equivalently environment variable `MINIWDL__FILE_IO__CHOWN=false`. I think this might be the source of the weird file ownership ex post facto. (The purpose of the chown feature is to make the files owned by the invoking user, but under Docker Desktop it might be having the opposite effect, due to its UID virtualization which you alluded to.)

**Comment by stxue1** [comment]
Ran into this issue again when updating my Docker Desktop version; when I originally reported this I swapped distros and the issue magically went away (possibly due to an updated Docker Desktop version but I'm not sure). Unfortunately I never kept track of which Docker Desktop versions this issue occurred with.

I updated recently again to Docker Desktop 4.29.0 (145265)
```
(venv) heaucques@pop-os:~/Documents/wdl-conformance-tests$ miniwdl --version
miniwdl v1.11.1
(venv) heaucques@pop-os:~/Documents/wdl-conformance-tests$ docker --version
Docker version 26.0.2, build 3c863ff
```

And now I get the exact same error:
```
Traceback (most recent call last):
  File "/home/heaucques/Documents/toil/venv/lib/python3.12/site-packages/WDL/runtime/task.py", line 224, in run_local_task
    chmod_R_plus(run_dir, file_bits=0o660, dir_bits=0o770)
  File "/home/heaucques/Documents/toil/venv/lib/python3.12/site-packages/WDL/_util.py", line 677, in chmod_R_plus
    do1(os.path.join(root, dn), dir_bits)
  File "/home/heaucques/Documents/toil/venv/lib/python3.12/site-packages/WDL/_util.py", line 668, in do1
    os.chmod(path1, (os.stat(path1).st_mode & 0o7777) | bits)
PermissionError: [Errno 1] Operation not permitted: '/tmp/miniwdl_run_self_test_7v8izbre/20240425_161629_hello_caller/download/0/work'
```
```
stat /tmp/miniwdl_run_self_test_7v8izbre/20240425_161629_hello_caller/download/0/work
  File: /tmp/miniwdl_run_self_test_7v8izbre/20240425_161629_hello_caller/download/0/work
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 10303h/66307d	Inode: 27148702    Links: 3
Access: (0775/drwxrwxr-x)  Uid: (100999/ UNKNOWN)   Gid: (100999/ UNKNOWN)
Access: 2024-04-25 16:16:29.834029254 -0700
Modify: 2024-04-25 16:16:30.810031665 -0700
Change: 2024-04-25 16:16:32.346035460 -0700
 Birth: 2024-04-25 16:16:29.834029254 -0700
```

However, I can confirm setting `MINIWDL__FIL_IO__CHOWN=false` circumvents this issue.

**Comment by anuragxxd** [comment]
Hit this from a different direction, which I think generalises the issue a bit.

I maintain an out-of-tree container backend (GA4GH TES, registered via the miniwdl.plugin.container_backend entry point https://github.com/anuragxxd/conquest). Task containers run as root against a shared volume; the miniwdl process itself runs as a non-root user. Same failure, same line no Docker Desktop and no UID virtualisation involved, just files in run_dir created by a different UID than the one calling chmod.

The reason I'm commenting rather than taking the documented workaround: MINIWDL__FILE_IO__CHOWN=false isn't reachable from a third-party backend. chown() is a backend method it's implemented in docker_swarm.py:571 (gated on that config at :579) and in podman.py. But chmod_R_plus() is called from run_local_task() at task.py:278, unconditionally and independently of the backend in use. So an out-of-tree backend gets the chmod without the compensating chown, and there's no setting that turns it off. For a backend whose outputs are produced by a remote executor on shared storage there's also no local equivalent you can't run a privileged container after the fact to correct ownership.

Given your earlier note that the chmod is there so downstream containers can still read the files if they drop privileges to an arbitrary UID "a bit of a corner case" would you take a PR making it best-effort?

```
def do1(path1: str, bits: int) -> None:
    assert 0 <= bits < 0o10000
    if not os.path.islink(path1) and path_really_within(path1, path):
        try:
            os.chmod(path1, (os.stat(path1).st_mode & 0o7777) | bits)
        except PermissionError:
            pass
```

Behaviour is unchanged everywhere it currently succeeds; it just stops a best-effort accessibility tweak from failing an otherwise-successful task. Happy to open it with a test. Two things I'd want your steer on: whether you'd prefer a debug-level log over swallowing silently (would mean threading a logger into chmod_R_plus), and whether the onerror=raiser on the os.walk at _util.py:710 should get the same treatment it doesn't bite in either repro here, since the directories are still traversable, but it's the same assumption.
