### ISSUE TITLE
Quoted numbers are not allowed in JSON but probably should be

### ISSUE THREAD

**Issue by adamnovak** [chanzuckerberg/miniwdl#646]
I tried to run a workflow via Toil that takes an `Int` input, and provided an inputs JSON where the value was a quoted string, parseable as an integer (in this case, `"10"`).

Unfortunately, MiniWDL's `values_from_json` rejects this saying that it `couldn't construct Int from "10"`.

```
Traceback (most recent call last):
  File "/private/groups/patenlab/anovak/workspace/toil/venv/lib/python3.10/site-packages/WDL/__init__.py", line 274, in values_from_json
    ans = ans.bind(key2, Value.from_json(ty, values_json[key]))
  File "/private/groups/patenlab/anovak/workspace/toil/venv/lib/python3.10/site-packages/WDL/Value.py", line 576, in from_json
    raise Error.InputError(f"couldn't construct {str(type)} from {json.dumps(value)}")
WDL.Error.InputError: couldn't construct Int from "10"
```

The wording of the error makes it sound like the program just isn't trying; `"10"` is something that Python itself can absolutely construct an integer from, so why can't `values_from_json` do it?

Insisting that integer inputs must be JSON `number`s is [consistent with the WDL spec](https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#json-input-format), but it might also be needlessly pedantic, and it means inputs that work on Terra or Cromwell perfectly fine will be rejected by MiniWDL.

Would it be possible to make the parser more permissive?

**Comment by mlin** [comment]
I personally find this debatable at best, but this is the relevant branch which would be very easy to adjust/amend:

https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/Value.py#L535-L536
