### ISSUE TITLE
Error running run_self_test in Ubuntu

### ISSUE THREAD

**Issue by duartetorreserick** [chanzuckerberg/miniwdl#657]
Hi, I got this error runing the run_self_test command

2023-09-16 18:52:27.239 miniwdl-run DEBUG read configuration defaults :: filename: "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/config_templates/default.cfg"
2023-09-16 18:52:27.240 miniwdl-run DEBUG searching for configuration files :: filenames: ["/home/erick/.config/miniwdl.cfg", "/etc/xdg/miniwdl.cfg", "/etc/xdg/xdg-ubuntu/miniwdl.cfg"]
2023-09-16 18:52:27.240 miniwdl-run INFO no configuration file found
2023-09-16 18:52:27.240 miniwdl-run DEBUG applying configuration overrides :: download_cache: {"get": "false"}, call_cache: {"get": "false"}, logging: {"json": "false"}
2023-09-16 18:52:27.241 miniwdl-run DEBUG configuration :: task_runtime: {"as_user": "false", "command_preamble": "", "env": "{}", "defaults": "{\n\"docker\": \"ubuntu:20.04\"\n}", "memory_limit_multiplier": "0.0", "command_shell": "/bin/bash", "allow_privileged": "false", "placeholder_regex": "(.|\\n)*", "download_defaults": "{\n\"cpu\": 2,\n\"memory\": \"1G\"\n}", "cpu_max": "0", "memory_max": "0"}, file_io: {"mount_tmpdir": "false", "allow_any_input": "false", "chown": "true", "copy_input_files": "false", "root": "/", "copy_input_files_for": "[]", "mount_tmpdir_for": "[]", "use_relative_output_paths": "false", "output_hardlinks": "false", "delete_work": "false"}, logging: {"json": "false"}, download_awscli: {"docker": "ghcr.io/miniwdl-ext/miniwdl-tools:Id_sha256_6cf3c7e37141ee50cbd692b872f4cbb92ecaab9eccc899263f6bcbea8f45a8b4", "host_credentials": "false"}, singularity: {"run_options": "[\n\"--containall\",\n\"--no-mount\", \"hostfs\",\n\"--fakeroot\"\n]", "image_cache": "", "exe": "[\"singularity\"]"}, udocker: {"exe": "[\"udocker\", \"--allow-root\"]", "run_options": "[\"--nobanner\", \"--rm\"]"}, plugins: {"disable_patterns": "[\"miniwdl_task_omnibus_example:*\"]", "enable_patterns": "[\"*\"]"}, podman: {"exe": "[\"sudo\", \"-n\", \"podman\"]"}, scheduler: {"subworkflow_concurrency": "0", "task_concurrency": "0", "container_backend": "docker_swarm", "download_concurrency": "0", "fail_fast": "true", "scatter_tag_max": "16"}, download_cache: {"flock": "true", "put": "false", "disable_patterns": "[\"*.php\", \"*.aspx\"]", "ignore_query": "false", "get": "false", "enable_patterns": "[\"*\"]", "dir": "/tmp/miniwdl_download_cache"}, docker_swarm: {"auto_init": "true", "server_error_retries": "2", "polling_period_seconds": "1.5", "allow_networks": "[]"}, call_cache: {"put": "false", "get": "false", "backend": "dir", "dir": "/home/erick/.cache/miniwdl"}, download_gsutil: {"docker": "gcr.io/google.com/cloudsdktool/cloud-sdk:442.0.0-slim"}, download_aria2c: {"docker": "ghcr.io/miniwdl-ext/miniwdl-tools:Id_sha256_6cf3c7e37141ee50cbd692b872f4cbb92ecaab9eccc899263f6bcbea8f45a8b4"}
2023-09-16 18:52:27.276 miniwdl-run DEBUG package versions :: python: "3.8.10 (default, May 26 2023, 14:05:08) \n[GCC 9.4.0]", uname: "Linux erick-Lenovo-ideapad-320-15IKB 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64", miniwdl: "1.11.0", docker: "6.1.3", lark: "1.1.7", argcomplete: "1.12.3", pygtail: "0.14.0"
2023-09-16 18:52:27.276 miniwdl-run DEBUG environment :: SHELL: "/bin/bash", miniwdl: "/home/erick/.local/bin/miniwdl", PWD: "/home/erick/Documentos/BIOINFORMATICA/CROMWELL/Lineal", HOME: "/home/erick", LANG: "es_CO.UTF-8", USER: "erick"
2023-09-16 18:52:27.327 miniwdl-run DEBUG plugin configuration :: enabled: ["s3 = WDL.runtime.download:awscli_downloader", "gs = WDL.runtime.download:gsutil_downloader", "s3 = WDL.runtime.download:awscli_directory_downloader", "gs = WDL.runtime.download:gsutil_directory_downloader", "docker_swarm = WDL.runtime.backend.docker_swarm:SwarmContainer", "singularity = WDL.runtime.backend.singularity:SingularityContainer", "podman = WDL.runtime.backend.podman:PodmanContainer", "udocker = WDL.runtime.backend.udocker:UdockerContainer", "dir = WDL.runtime.cache:CallCache"], disabled: []
2023-09-16 18:52:27.337 wdl.w:hello_caller NOTICE workflow start :: name: "hello_caller", source: "/tmp/miniwdl_run_self_test_m73n_tk5/test.wdl", line: 3, column: 13, dir: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller"
2023-09-16 18:52:27.337 wdl.w:hello_caller DEBUG thread :: ident: 140484688246592
2023-09-16 18:52:27.337 miniwdl-run.CallCache.FlockHolder DEBUG flock :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/workflow.log", realpath: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/workflow.log", exclusive: true, wait: false
2023-09-16 18:52:27.337 miniwdl-run.CallCache.FlockHolder DEBUG flocked :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/workflow.log", realpath: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/workflow.log", exclusive: true, name_inode: 3936056, fd_inode: 3936056
2023-09-16 18:52:27.340 wdl.w:hello_caller NOTICE miniwdl :: version: "v1.11.0", uname: "Linux erick-Lenovo-ideapad-320-15IKB 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64"
2023-09-16 18:52:27.349 wdl.w:hello_caller NOTICE downloading input URIs :: count: 1
2023-09-16 18:52:27.349 wdl.w:hello_caller INFO schedule input file download :: uri: "https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt"
2023-09-16 18:52:27.350 wdl.w:hello_caller.CallCache DEBUG no download cache hit :: uri: "https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt", cache_path: "/tmp/miniwdl_download_cache/files/https/raw.githubusercontent.com/_chanzuckerberg_miniwdl_main_tests/alyssa_ben.txt"
2023-09-16 18:52:27.350 wdl.w:hello_caller INFO start download :: uri: "https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt"
2023-09-16 18:52:27.575 wdl.w:hello_caller.download0.t:download-aria2c NOTICE task setup :: name: "aria2c", source: "", line: 2, column: 5, dir: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0", thread: 140484647814912
2023-09-16 18:52:27.576 wdl.w:hello_caller.download0.t:download-aria2c.CallCache.FlockHolder DEBUG flock :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0/task.log", realpath: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0/task.log", exclusive: true, wait: false
2023-09-16 18:52:27.576 wdl.w:hello_caller.download0.t:download-aria2c.CallCache.FlockHolder DEBUG flocked :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0/task.log", realpath: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0/task.log", exclusive: true, name_inode: 3936059, fd_inode: 3936059
2023-09-16 18:52:27.727 docker.utils.config DEBUG Trying paths: ['/home/erick/.docker/config.json', '/home/erick/.dockercfg']
2023-09-16 18:52:27.727 docker.utils.config DEBUG No config file found
2023-09-16 18:52:27.727 docker.utils.config DEBUG Trying paths: ['/home/erick/.docker/config.json', '/home/erick/.dockercfg']
2023-09-16 18:52:27.727 docker.utils.config DEBUG No config file found
2023-09-16 18:52:27.731 wdl.w:hello_caller.download0.t:download-aria2c DEBUG Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task.py", line 170, in run_local_task
    container = new_task_container(cfg, logger, run_id, run_dir)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task_container.py", line 531, in new
    backend_cls.global_init(cfg, logger)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/backend/docker_swarm.py", line 40, in global_init
    client = docker.from_env(version="auto")
  File "/home/erick/.local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/erick/.local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

2023-09-16 18:52:27.731 wdl.w:hello_caller.download0.t:download-aria2c ERROR task aria2c ( Ln 2 Col 5) failed :: dir: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0", error: "DockerException", message: "Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))", traceback: ["Traceback (most recent call last):", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 790, in urlopen", "    response = self._make_request(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 496, in _make_request", "    conn.request(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py\", line 395, in request", "    self.endheaders()", "  File \"/usr/lib/python3.8/http/client.py\", line 1251, in endheaders", "    self._send_output(message_body, encode_chunked=encode_chunked)", "  File \"/usr/lib/python3.8/http/client.py\", line 1011, in _send_output", "    self.send(msg)", "  File \"/usr/lib/python3.8/http/client.py\", line 951, in send", "    self.connect()", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py\", line 27, in connect", "    sock.connect(self.unix_socket)", "ConnectionRefusedError: [Errno 111] Connection refused", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py\", line 486, in send", "    resp = conn.urlopen(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 844, in urlopen", "    retries = retries.increment(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 470, in increment", "    raise reraise(type(error), error, _stacktrace)", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/util/util.py\", line 38, in reraise", "    raise value.with_traceback(tb)", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 790, in urlopen", "    response = self._make_request(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 496, in _make_request", "    conn.request(", "  File \"/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py\", line 395, in request", "    self.endheaders()", "  File \"/usr/lib/python3.8/http/client.py\", line 1251, in endheaders", "    self._send_output(message_body, encode_chunked=encode_chunked)", "  File \"/usr/lib/python3.8/http/client.py\", line 1011, in _send_output", "    self.send(msg)", "  File \"/usr/lib/python3.8/http/client.py\", line 951, in send", "    self.connect()", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py\", line 27, in connect", "    sock.connect(self.unix_socket)", "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py\", line 214, in _retrieve_server_version", "    return self.version(api_version=False)[\"ApiVersion\"]", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/api/daemon.py\", line 181, in version", "    return self._result(self._get(url), json=True)", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/utils/decorators.py\", line 46, in inner", "    return f(self, *args, **kwargs)", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py\", line 237, in _get", "    return self.get(url, **self._set_request_timeout(kwargs))", "  File \"/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py\", line 602, in get", "    return self.request(\"GET\", url, **kwargs)", "  File \"/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py\", line 589, in request", "    resp = self.send(prep, **send_kwargs)", "  File \"/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py\", line 703, in send", "    r = adapter.send(request, **kwargs)", "  File \"/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py\", line 501, in send", "    raise ConnectionError(err, request=request)", "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task.py\", line 170, in run_local_task", "    container = new_task_container(cfg, logger, run_id, run_dir)", "  File \"/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task_container.py\", line 531, in new", "    backend_cls.global_init(cfg, logger)", "  File \"/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/backend/docker_swarm.py\", line 40, in global_init", "    client = docker.from_env(version=\"auto\")", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/client.py\", line 96, in from_env", "    return cls(", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/client.py\", line 45, in __init__", "    self.api = APIClient(*args, **kwargs)", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py\", line 197, in __init__", "    self._version = self._retrieve_server_version()", "  File \"/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py\", line 221, in _retrieve_server_version", "    raise DockerException(", "docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"]
2023-09-16 18:52:27.732 wdl.w:hello_caller.download0.t:download-aria2c.CallCache.FlockHolder DEBUG close :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/download/0/task.log", exclusive: true
2023-09-16 18:52:27.732 wdl.w:hello_caller NOTICE aborting workflow
2023-09-16 18:52:27.733 wdl.w:hello_caller DEBUG Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/erick/.local/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task.py", line 170, in run_local_task
    container = new_task_container(cfg, logger, run_id, run_dir)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/task_container.py", line 531, in new
    backend_cls.global_init(cfg, logger)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/backend/docker_swarm.py", line 40, in global_init
    client = docker.from_env(version="auto")
  File "/home/erick/.local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/erick/.local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/erick/.local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/workflow.py", line 976, in _workflow_main_loop
    _download_input_files(
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/workflow.py", line 1196, in _download_input_files
    raise exn
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/download.py", line 146, in run_cached
    filename = run(cfg, logger, uri, directory=directory, run_dir=run_dir, **kwargs)
  File "/home/erick/.local/lib/python3.8/site-packages/WDL/runtime/download.py", line 117, in run
    raise DownloadFailed(uri) from exn.__cause__
WDL.runtime.error.DownloadFailed: unable to download https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt

2023-09-16 18:52:27.733 wdl.w:hello_caller ERROR workflow hello_caller (/tmp/miniwdl_run_self_test_m73n_tk5/test.wdl Ln 3 Col 13) failed :: dir: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller", error: "DownloadFailed", message: "unable to download https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt"
2023-09-16 18:52:27.733 miniwdl-run ERROR unable to download https://raw.githubusercontent.com/chanzuckerberg/miniwdl/main/tests/alyssa_ben.txt :: error: "DownloadFailed", dir: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller"
2023-09-16 18:52:27.734 miniwdl-run.CallCache.FlockHolder DEBUG close :: file: "/tmp/miniwdl_run_self_test_m73n_tk5/20230916_185227_hello_caller/workflow.log", exclusive: true

**Comment by mlin** [comment]
@duartetorreserick appears from this like Docker isn't available on the machine, is that plausible?

```
File "/home/erick/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 27, in connect
sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused
```
