### ISSUE TITLE
UnboundLocalError: local variable 'ans' referenced before assignment

### ISSUE THREAD

**Issue by pkaleta** [chanzuckerberg/miniwdl#97]
```
Traceback (most recent call last):
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 900, in load
    import_uri=import_uri,
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 906, in load
    doc.typecheck(check_quant=check_quant)
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 868, in typecheck
    self.workflow.typecheck(self, check_quant=check_quant)
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 734, in typecheck
    if errors.try1(lambda: _typecheck_workflow_elements(doc, check_quant)) == False:
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Error.py", line 227, in try1
    return fn()
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 734, in <lambda>
    if errors.try1(lambda: _typecheck_workflow_elements(doc, check_quant)) == False:
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 1059, in _typecheck_workflow_elements
    lambda child=child: _typecheck_workflow_elements(
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Error.py", line 227, in try1
    return fn()
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 1060, in <lambda>
    doc, check_quant, child
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 1051, in _typecheck_workflow_elements
    lambda child=child: child.typecheck_input(self._type_env, check_quant)
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Error.py", line 227, in try1
    return fn()
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 1051, in <lambda>
    lambda child=child: child.typecheck_input(self._type_env, check_quant)
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 375, in typecheck_input
    lambda expr=expr, decl=decl: expr.infer_type(
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Error.py", line 227, in try1
    return fn()
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Tree.py", line 376, in <lambda>
    type_env, check_quant
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Expr.py", line 70, in infer_type
    errors.try1(lambda: child.infer_type(type_env, check_quant))
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Error.py", line 227, in try1
    return fn()
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Expr.py", line 70, in <lambda>
    errors.try1(lambda: child.infer_type(type_env, check_quant))
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Expr.py", line 73, in infer_type
    self._type = self._infer_type(type_env)
  File "/Users/piotr/counsyl/seq_pipeline/.frak-venv/lib/python3.6/site-packages/WDL/Expr.py", line 571, in _infer_type
    if isinstance(ans, T.Pair):
UnboundLocalError: local variable 'ans' referenced before assignment
```

**Comment by pkaleta** [comment]
See https://github.com/chanzuckerberg/miniwdl/pull/98
